#server
server:
  port: 8880

#datasource
spring:
  application:
    name: examService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.16.233:3306/bh_exam?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    #url: jdbc:mysql://127.0.0.1:3306/bh_exam?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: bh_exam
    password: 4YH8hCwacK64L2wh
    #password: iZKMakKWwHpZmcNf

#mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
